version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: langfuse
      POSTGRES_PASSWORD: langfuse
      POSTGRES_DB: langfuse
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  langfuse:
    image: ghcr.io/langfuse/langfuse:2.95
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      NEXTAUTH_SECRET: changeme
      DATABASE_URL: postgres://langfuse:langfuse@postgres:5432/langfuse
      NEXTAUTH_URL: http://localhost:3000             # ← 追加①
      SALT: a7ed03e7a2fa467baf74e9c3a4b6dede  
      SENTRY_DSN: ""
      SENTRY_AUTO_UPLOAD_SOURCE_MAPS: "false"
    volumes:
      - ./langfuse_data:/data