services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: langfuse
      POSTGRES_PASSWORD: langfuse
      POSTGRES_DB: langfuse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U langfuse"]
      interval: 5s
      timeout: 5s
      retries: 5

  langfuse:
    image: ghcr.io/langfuse/langfuse:2.95
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      NEXTAUTH_SECRET: changeme
      DATABASE_URL: postgres://langfuse:langfuse@postgres:5432/langfuse
      NEXTAUTH_URL: http://localhost:3000
      SALT: a7ed03e7a2fa467baf74e9c3a4b6dede  
      SENTRY_DSN: ""
      SENTRY_AUTO_UPLOAD_SOURCE_MAPS: "false"

volumes:
  postgres_data: